name: Test and Lint

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64' # (x64 or x86)

    - name: Setup venv
      run: python -m venv ~/.venv

    - name: Install dependencies
      run: |
        source ~/.venv/bin/activate
        pip install poetry
        poetry install

    - name: Check code formatting
      run: |
        source ~/.venv/bin/activate
        python -m black picobrew_server
    
    - name: Lint code
      run: |
        source ~/.venv/bin/activate
        python -m pylint picobrew_server

    - name: Check typing
      run: |
        source ~/.venv/bin/activate
        python -m mypy picobrew_server

  